version: '3'

name: 'rms-project'
services:
  db:
    image: 'mysql/mysql-server:8.0'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: 'rms_app'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'password'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'db:/var/lib/mysql'
    networks:
      - 'app'

#  redis:
#    image: 'redis:alpine'
#    ports:
#      - '${FORWARD_REDIS_PORT:-6379}:6379'
#    volumes:
#      - 'app-redis:/data'
#    networks:
#      - app
#    healthcheck:
#      test: ['CMD', 'redis-cli', 'ping']
#      retries: 3
#      timeout: 5s

networks:
  app:
    driver: bridge

volumes:
  db:
    driver: local
#  app-redis:
#    driver: local