spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/rms_app'
    username: 'admin'
    password: 'password'
    driver-class-name: 'com.mysql.cj.jdbc.Driver'
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    database: mysql
    defer-datasource-initialization: true
#    open-in-view: false
  sql:
    init:
      mode: always
  jackson:
    mapper:
      propagate-transient-marker: true

server:
  error:
    include-message: always

application:
  security:
    jwt:
      secret_key: qWJN7VpeVkSXawfIosC8qajApwILsG8P
      expiration: 43200000

#  data:
#    redis:
#      host: 'localhost'
#      port: 6379